Set ROOT from command-line option or environment variable.

diff --git a/minpkg b/minpkg
--- a/minpkg
+++ b/minpkg
@@ -26,85 +26,85 @@ assert_writable () {
 }
 
 pkg_init () {
-    if [ "$#" -ne 1 ]
+    if [ "$#" -ne 0 ]
     then
-        fail "usage: $0 init ROOT"
+        fail "usage: $0 init"
     fi
 
-    if [ ! -d "$1" ]
+    if [ ! -d "$MINPKG_ROOT" ]
     then
-        fail "$1 is not a directory"
+        fail "$MINPKG_ROOT not a directory"
     fi
 
-    assert_writable "$1"
+    assert_writable "$MINPKG_ROOT"
 
-    if [ -d "$1/etc/pkg/list" ]
+    if [ -d "$MINPKG_ROOT/etc/pkg/list" ]
     then
-        fail "$1 is already initialized"
+        fail "$MINPKG_ROOT is already initialized"
     fi
 
-    mkdir -p "$1/etc/pkg/list"
-    touch "$1/etc/pkg/PACKAGES"
-    touch "$1/etc/pkg/CONFLICT"
-    mkdir -p "$1/bin"
-    cp "$0" "$1/bin/"
+    mkdir -p "$MINPKG_ROOT/etc/pkg/list"
+    touch "$MINPKG_ROOT/etc/pkg/PACKAGES"
+    touch "$MINPKG_ROOT/etc/pkg/CONFLICT"
+    mkdir -p "$MINPKG_ROOT/bin"
+    cp "$0" "$MINPKG_ROOT/bin/"
 }
 
 pkg_list () {
-    if [ "$#" -ne 1 ]
+    if [ "$#" -ne 0 ]
     then
-        fail "usage: $0 list ROOT"
+        fail "usage: $0 list"
     fi
 
-    plist="$1/etc/pkg/PACKAGES"
+    plist="$MINPKG_ROOT/etc/pkg/PACKAGES"
 
-    assert_readable "$1"
+    assert_readable "$MINPKG_ROOT"
 
     if [ -f "$plist" ]
     then
         cat "$plist"
         return 0
     else
-        fail "unable to find package information on $1"
+        fail "unable to find package information on $MINPKG_ROOT"
     fi
 }
 
 pkg_add () {
-    if [ "$#" -ne 2 ]
+    if [ "$#" -ne 1 ]
     then
-        fail "usage: $0 add ROOT PKGFILE"
+        fail "usage: $0 add PKGFILE"
     fi
 
-    assert_writable "$1"
+    assert_writable "$MINPKG_ROOT"
 
-    if [ ! -f "$2" ]
+    if [ ! -f "$1" ]
     then
-        fail "file not found: $2"
+        fail "file not found: $1"
     fi
 
-    pkgid=`basename "$2" .tgz`
-    flist="$1/etc/pkg/list/$pkgid"
+    pkgid=`basename "$1" .tgz`
+    flist="$MINPKG_ROOT/etc/pkg/list/$pkgid"
 
     if [ -f "$flist" ]
     then
-        fail "$pkgid is already installed on $1"
+        fail "$pkgid is already installed on $MINPKG_ROOT"
     fi
 
-    plist="$1/etc/pkg/PACKAGES"
-    confl="$1/etc/pkg/CONFLICT"
+    plist="$MINPKG_ROOT/etc/pkg/PACKAGES"
+    confl="$MINPKG_ROOT/etc/pkg/CONFLICT"
 
-    pkg_to "$2" > "$flist"
+    pkg_to "$1" > "$flist"
 
     add=0
     mod=0
     while read path
     do
-        if [ -e "$1/$path" ]
+        if [ -e "$MINPKG_ROOT/$path" ]
         then
-            from=`pkg_from "$1" "$path" 2> /dev/null`
+            from=`pkg_from "$path" 2> /dev/null`
             if [ $? -eq 0 ]
             then
-                mv "$1/$path" "$1/$path.$from"
+                mv "$MINPKG_ROOT/$path" "$MINPKG_ROOT/$path.$from"
                 if ! grep -qF "$path" "$confl"
                 then
                     printf "$path\n" >> "$confl"
@@ -119,7 +119,7 @@ pkg_add () {
         fi
     done < "$flist"
 
-    tar -x -z -C "$1" -f "$2"
+    tar -x -z -C "$MINPKG_ROOT" -f "$1"
 
     printf "$pkgid\n" >> "$plist"
 
@@ -131,33 +131,33 @@ pkg_add () {
 }
 
 pkg_del () {
-    if [ "$#" -ne 2 ]
+    if [ "$#" -ne 1 ]
     then
-        fail "usage: $0 del ROOT PKGID"
+        fail "usage: $0 del PKGID"
     fi
 
-    assert_writable "$1"
+    assert_writable "$MINPKG_ROOT"
 
-    pkgid=`basename "$2" .tgz`
-    flist="$1/etc/pkg/list/$pkgid"
+    pkgid=`basename "$1" .tgz`
+    flist="$MINPKG_ROOT/etc/pkg/list/$pkgid"
 
     if [ ! -f "$flist" ]
     then
-        fail "$pkgid is not installed on $1"
+        fail "$pkgid is not installed on $MINPKG_ROOT"
     fi
 
-    plist="$1/etc/pkg/PACKAGES"
-    confl="$1/etc/pkg/CONFLICT"
+    plist="$MINPKG_ROOT/etc/pkg/PACKAGES"
+    confl="$MINPKG_ROOT/etc/pkg/CONFLICT"
 
     sub=0
     mod=0
     hid=0
-    match="$1/etc/pkg/MATCH"
+    match="$MINPKG_ROOT/etc/pkg/MATCH"
     while read path
     do
         if grep -qF "$path" "$confl"
         then
-            pkg_match "$1" "$path" > "$match"
+            pkg_match "$path" > "$match"
             count=`wc -l < "$match"`
             if [ $count -le 2 ]
             then
@@ -168,16 +168,16 @@ pkg_del () {
             if [ "$from" = "$pkgid" ]
             then
                 below=`sed -n '2p' "$match"`
-                mv "$1/$path.$below" "$1/$path"
+                mv "$MINPKG_ROOT/$path.$below" "$MINPKG_ROOT/$path"
                 printf "unmasked %s %s\n" "$below" "$path" >&2
                 mod=$((mod+1))
             else
-                rm "$1/$path.$pkgid"
+                rm "$MINPKG_ROOT/$path.$pkgid"
                 hid=$((hid+1))
             fi
         else
-            rm "$1/$path"
-            dirpath=`dirname "$1/$path"`
+            rm "$MINPKG_ROOT/$path"
+            dirpath=`dirname "$MINPKG_ROOT/$path"`
             while rmdir "$dirpath" 2> /dev/null
             do
                 dirpath=`dirname "$dirpath"`
@@ -218,28 +218,28 @@ pkg_to () {
 }
 
 pkg_from () {
-    if [ "$#" -ne 2 ]
+    if [ "$#" -ne 1 ]
     then
-        fail "usage: $0 from ROOT PATH"
+        fail "usage: $0 from PATH"
     fi
 
-    assert_readable "$1"
+    assert_readable "$MINPKG_ROOT"
 
-    plist="$1/etc/pkg/PACKAGES"
+    plist="$MINPKG_ROOT/etc/pkg/PACKAGES"
 
     if [ ! -f "$plist" ]
     then
-        fail "unable to find package information on $1"
+        fail "unable to find package information on $MINPKG_ROOT"
     fi
 
-    if [ ! -e "$1/$2" ]
+    if [ ! -e "$MINPKG_ROOT/$1" ]
     then
-        fail "$2 does not exist on $1"
+        fail "$1 does not exist on $MINPKG_ROOT"
     fi
 
     tac "$plist" | while read pkg
     do
-        if grep -qF "$2" "$1/etc/pkg/list/$pkg"
+        if grep -qF "$1" "$MINPKG_ROOT/etc/pkg/list/$pkg"
         then
             printf "$pkg\n"
             exit 1
@@ -248,34 +248,34 @@ pkg_from () {
 
     if [ $? -eq 0 ]
     then
-        fail "$2 was not installed from package"
+        fail "$1 was not installed from package"
     fi
 }
 
 pkg_match () {
-    if [ "$#" -ne 2 ]
+    if [ "$#" -ne 1 ]
     then
-        fail "usage: $0 match ROOT PATH"
+        fail "usage: $0 match PATH"
     fi
 
-    assert_readable "$1"
+    assert_readable "$MINPKG_ROOT"
 
-    plist="$1/etc/pkg/PACKAGES"
+    plist="$MINPKG_ROOT/etc/pkg/PACKAGES"
 
     if [ ! -f "$plist" ]
     then
-        fail "unable to find package information on $1"
+        fail "unable to find package information on $MINPKG_ROOT"
     fi
 
     # the shortcut below is not working from del for unknown reasons
-    #~ if [ ! -e "$1/$2" ]
+    #~ if [ ! -e "$MINPKG_ROOT/$1" ]
     #~ then
-        #~ fail "$1/$2 does not seem to exist"
+        #~ fail "$MINPKG_ROOT/$1 does not seem to exist"
     #~ fi
 
     tac "$plist" | while read pkg
     do
-        if grep -qF "$2" "$1/etc/pkg/list/$pkg"
+        if grep -qF "$1" "$MINPKG_ROOT/etc/pkg/list/$pkg"
         then
             printf "$pkg\n"
         fi
@@ -283,35 +283,35 @@ pkg_match () {
 }
 
 pkg_raise () {
-    if [ "$#" -ne 2 ]
+    if [ "$#" -ne 1 ]
     then
-        fail "usage: $0 raise ROOT PKGID" >&2
+        fail "usage: $0 raise PKGID" >&2
     fi
 
-    assert_writable "$1"
+    assert_writable "$MINPKG_ROOT"
 
-    pkgid=`basename "$2" .tgz`
-    flist="$1/etc/pkg/list/$pkgid"
+    pkgid=`basename "$1" .tgz`
+    flist="$MINPKG_ROOT/etc/pkg/list/$pkgid"
 
     if [ ! -f "$flist" ]
     then
-        fail "$pkgid is not installed on $1"
+        fail "$pkgid is not installed on $MINPKG_ROOT"
     fi
 
-    plist="$1/etc/pkg/PACKAGES"
-    confl="$1/etc/pkg/CONFLICT"
+    plist="$MINPKG_ROOT/etc/pkg/PACKAGES"
+    confl="$MINPKG_ROOT/etc/pkg/CONFLICT"
 
     mod=0
-    raise="$1/etc/pkg/RAISE"
+    raise="$MINPKG_ROOT/etc/pkg/RAISE"
     cat "$flist" "$confl" | sort | uniq -d > "$raise"
     while read path
     do
-        from=`pkg_from "$1" "$path"`
+        from=`pkg_from "$path"`
         if [ "$from" != "$pkgid" ]
         then
-            mv "$1/$path" "$1/$path.$from"
+            mv "$MINPKG_ROOT/$path" "$MINPKG_ROOT/$path.$from"
             printf "masked %s %s\n" "$from" "$path" >&2
-            mv "$1/$path.$pkgid" "$1/$path"
+            mv "$MINPKG_ROOT/$path.$pkgid" "$MINPKG_ROOT/$path"
             mod=$((mod+1))
         fi
     done < "$raise"
@@ -323,6 +323,17 @@ pkg_raise () {
 
     printf "modified %d files\n" "$mod"
 }
+
+if [ ! -d "$MINPKG_ROOT" ]
+then
+    MINPKG_ROOT="$PWD"
+fi
+
+if [ "$1" = "-r" ]
+then
+    MINPKG_ROOT="$2"
+    shift 2
+fi
 
 cmd="$1"
 shift
